[Feature] Forms de advogado e entregador
idvogados/idvogados.github.io pull request #16
Opened 2020-05-12 13:00 UTC by mastercoks

### Descrição das Mudanças ###

Foram adicionado duas páginas com os formulários embutidos, esses formulários serão utilizados para pesquisas quantitativas.

- Relacionado a issue #15 

### Mudanças na API ###

*Nenhuma*

### Mudanças de comportamento ###

O usuário irá clicar nos botões localizados na home e serão redirecionados para essas páginas.

### Testing Procedure ###

*Nenhum*

### PR Checklist ###

- [ ] Possui testes (se não, por favor descreva o motivo de não ter teste)
- [ ] Foi feito Rebase para a master no momento que o PR foi aberto
- [ ] Modificações estão de acordo com o padrão de código
- [ ] Atualizado documentação

### PR Checklist  do time ###

- [ ] O PR está apontando para a branch correta
- [ ] Os testes estão passando (ou as falha não são relacionadas a este PR)

2020-05-12 13:05 UTC, mastercoks commented
Caso precise validar como ficaram essas mudanças, favor olhar o site https://mastercoks.github.io/idvogados.github.io/

2020-05-12 23:02 UTC, pictos commented
@rodrigondec esse erro da automação é esperado?

2020-05-12 23:22 UTC, Gerlison submitted a review, later dismissed

2020-05-12 23:23 UTC, Gerlison commented
Deixando o aprove aqui já que o erro na automação não é relacionado ao PR.

2020-05-12 23:40 UTC, rodrigondec commented
> @rodrigondec esse erro da automação é esperado?

Abri o issue alex-page/github-project-automation-plus#39 na action que está sendo utilizada. 

É um problema com o octokit utilizado lá no script.

2020-05-12 23:48 UTC, rodrigondec requested changes
Visualizando no meu navegador ficou quebrado o embed dos forms
 ![image](https://user-images.githubusercontent.com/3301060/81756318-c8e76c80-9491-11ea-9e00-a141b9676908.png)

2020-05-12 23:56 UTC, mastercoks commented
> Visualizando no meu navegador ficou quebrado o embed dos forms
> ![image](https://user-images.githubusercontent.com/3301060/81756318-c8e76c80-9491-11ea-9e00-a141b9676908.png)

Eu na pressa acabei n validando pra firefox, já vou ajeitar.

2020-05-13 00:18 UTC, mastercoks commented
@rodrigondec favor testar novamente.

2020-05-14 12:56 UTC, rodrigondec commented
> @rodrigondec favor testar novamente.
Show! Os dois estão ok

![image](https://user-images.githubusercontent.com/3301060/81936853-30ec9e80-95c9-11ea-9c72-77e81f3b23f0.png)

2020-05-14 12:57 UTC, rodrigondec approved these changes

2020-05-14 23:23 UTC, pictos commented
Como já foi corrigido todos os erros apontados e a agenda está apertada irei fazer o merge desse PR sem o número mínimo de aprovações.

@mastercoks muito obg pela contribuição❣️

![image](https://user-images.githubusercontent.com/20712372/81995443-c2d3c600-9620-11ea-993c-44bb3697d419.png)

2020-05-14 23:24 UTC, merged