init: Estrutura inicial do blog
idvogados/idvogados.github.io pull request #17
Opened 2020-06-30 01:58 UTC by mastercoks

### Descrição das Mudanças ###

Foi implementado a estrutura do blog
- Relacionado a issue #3

### PR Checklist ###

- [ ] Possui testes (se não, por favor descreva o motivo de não ter teste)
- [x] Foi feito Rebase para a master no momento que o PR foi aberto
- [x] Modificações estão de acordo com o padrão de código
- [ ] Atualizado documentação

### PR Checklist  do time ###

- [ ] O PR está apontando para a branch correta
- [ ] Os testes estão passando (ou as falha não são relacionadas a este PR)

2020-06-30 03:35 UTC, pabrrs requested changes
Muito bom @mastercoks :tada:

Não tenho muito a acrescentar, apenas algumas considerações básicas. 

Seria ótimo se no README do projeto, fossem adicionas instruções de como rodar local e/ou com docker. Isso não impede de subir, pode ficar em outra task.

Assim que a nova versão estiver pronta, com os padrões do wireframe definidos pelo time de Design, posso deixar mais comentários.

2020-06-30 03:35 UTC, pabrrs commented on _authors/mastercoks.md
> +---
Sugiro colocar os dados da entidade iDvogados.

2020-06-30 03:35 UTC, pabrrs commented on _includes/recommendation.html
> +        <strong>{{ site.translations.recommendation.text | default: "Why don't you read something next?" }}</strong>
Sugiro traduzir esse texto

2020-06-30 03:35 UTC, pabrrs commented on _includes/recommendation.html
> +                <span>{{ site.translations.recommendation.back_btn | default: "Go back to top" }}</span>
Sugiro traduzir esse também

2020-06-30 10:55 UTC, mastercoks commented on _authors/mastercoks.md
> +---
Essa parte vai ser retirada na versão final, só coloquei para efeito de teste, já que não tinha as infos dos autores reais.

2020-06-30 10:56 UTC, mastercoks commented on _includes/recommendation.html
> +        <strong>{{ site.translations.recommendation.text | default: "Why don't you read something next?" }}</strong>
Essa parte de recomendação vai ser retirada (esqueci de apagar o arquivo)

2020-06-30 10:56 UTC, mastercoks commented on _includes/recommendation.html
> +                <span>{{ site.translations.recommendation.back_btn | default: "Go back to top" }}</span>
Essa parte de recomendação vai ser retirada (esqueci de apagar o arquivo)

2020-06-30 11:00 UTC, mastercoks commented
> Muito bom @mastercoks 🎉
> 
> Não tenho muito a acrescentar, apenas algumas considerações básicas.
> 
> Seria ótimo se no README do projeto, fossem adicionas instruções de como rodar local e/ou com docker. Isso não impede de subir, pode ficar em outra task.
> 
> Assim que a nova versão estiver pronta, com os padrões do wireframe definidos pelo time de Design, posso deixar mais comentários.

Obrigado pelo feedback!
Eu pretendo fazer uma wiki com todas informações sobre o projeto.
Elas estão basicamente aqui https://github.com/thiagorossener/jekflix-template/wiki, só falta traduzir para PT-BR e adaptar as coisas que eu alterei.

2020-07-01 15:43 UTC, rodrigondec reviewed
Gostei muito :rocket:.

Não olhei muito os HTML's, então não considerar minha opnião sobre eles :sweat_smile: .

Tirando os pontos já mencionados sobre tradução, surgiu apenas algumas dúvidas. Mas nada muito problemático.

2020-07-01 15:43 UTC, rodrigondec commented on _config.yml
> +google_analytics: "UA-XXXXXXXX-X"
Tem alguma forma de deixar isso em um env ou algo similar?

2020-07-01 15:43 UTC, rodrigondec commented on yarn-error.log
> +PATH:
Precisa ter esse log mesmo?

2020-07-01 15:55 UTC, mastercoks commented on _config.yml
> +google_analytics: "UA-XXXXXXXX-X"
Eu irei da uma pesquisada, acredito que dê para fazer, pois eu uso gulp para essas configurações aí, ao preciso verificar.
Como essa não é uma demanda urgente, vou deixar para olhar após terminar os outros detalhes.
Obrigado pelo feedback!

2020-07-01 15:56 UTC, mastercoks commented on yarn-error.log
> +PATH:
Não, acabou que eu não vi que ele existia kkkk, vou apagar e adicionar no .gitignore

2020-07-02 19:30 UTC, deniojunior commented on _config.yml
> +google_analytics: "UA-XXXXXXXX-X"
Se não tiver uma solução mais simples que dê pra usar uma env var dentro do `_config.yaml`, dá pra deixar um placeholder no aquivo e adicionar um step no CI para substituir no arquivo com o valor da secret.

2020-07-02 19:30 UTC, deniojunior commented on _layouts/404.html
> +  <p>{{ site.translations.error_404.message | default: "Eu sinto muito. Não foi possível encontrar a página que você estava procurando.." }}</p>
Tá só com dois pontos no final, ao invés de três. Detalhezinho irrelevante rsrs

2020-07-02 19:30 UTC, deniojunior commented on _posts/2013-12-12-smoke-alert.md
> +Cas sociis natoque penatibus et magnis <a href="#">dis parturient montes</a>, nascetur ridiculus mus. *Aenean eu leo quam.* Pellentesque ornare sem lacinia quam venenatis vestibulum. Sed posuere cons
Esse arquivo é necessário?

2020-07-02 19:30 UTC, deniojunior commented on _posts/2013-12-12-smoke-alert copy.md
> +Vivamus sagittis lacus vel augue rutrum faucibus dolor auctor. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Morbi leo risus, porta ac consectetur a
Esse arquivo é necessário?

2020-07-02 19:30 UTC, deniojunior commented on _posts/2013-12-12-smoke-alert copy 5.md
> +Aenean lacinia bibendum nulla sed consectetur. Etiam porta sem malesuada magna mollis euismod. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa.
Esse arquivo é necessário?

2020-07-02 19:30 UTC, deniojunior commented on _posts/2013-12-12-smoke-alert copy 4.md
> +Aenean lacinia bibendum nulla sed consectetur. Lorem ipsum dolor sit amet, consectetur adipiscing elit.
Esse arquivo é necessário?

2020-07-02 19:30 UTC, deniojunior commented on _posts/2013-12-12-smoke-alert copy 3.md
> +Aenean lacinia bibendum nulla sed consectetur. Lorem ipsum dolor sit amet, consectetur adipiscing elit.
Esse arquivo é necessário?

2020-07-02 19:30 UTC, deniojunior commented on _posts/2013-12-12-smoke-alert copy 2.md
> +Nullam id dolor id nibh ultricies vehicula ut id elit. Sed posuere consectetur est at lobortis. Nullam quis risus eget urna mollis ornare vel eu leo.
Esse arquivo é necessário?

2020-07-03 06:26 UTC, mastercoks commented on _posts/2013-12-12-smoke-alert copy 2.md
> +Nullam id dolor id nibh ultricies vehicula ut id elit. Sed posuere consectetur est at lobortis. Nullam quis risus eget urna mollis ornare vel eu leo.
Não, era apenas para não ficar em branco, e poder ver como ficou o layout.
Porém eu removi.

2020-07-03 06:26 UTC, mastercoks commented on _posts/2013-12-12-smoke-alert copy 3.md
> +Aenean lacinia bibendum nulla sed consectetur. Lorem ipsum dolor sit amet, consectetur adipiscing elit.
Não, era apenas para não ficar em branco, e poder ver como ficou o layout.
Porém eu removi.

2020-07-03 06:26 UTC, mastercoks commented on _posts/2013-12-12-smoke-alert copy 4.md
> +Aenean lacinia bibendum nulla sed consectetur. Lorem ipsum dolor sit amet, consectetur adipiscing elit.
Não, era apenas para não ficar em branco, e poder ver como ficou o layout.
Porém eu removi.

2020-07-03 06:26 UTC, mastercoks commented on _posts/2013-12-12-smoke-alert copy 5.md
> +Aenean lacinia bibendum nulla sed consectetur. Etiam porta sem malesuada magna mollis euismod. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa.
Não, era apenas para não ficar em branco, e poder ver como ficou o layout.
Porém eu removi.

2020-07-03 06:26 UTC, mastercoks commented on _posts/2013-12-12-smoke-alert copy.md
> +Vivamus sagittis lacus vel augue rutrum faucibus dolor auctor. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Morbi leo risus, porta ac consectetur a
Não, era apenas para não ficar em branco, e poder ver como ficou o layout.
Porém eu removi.

2020-07-03 06:26 UTC, mastercoks commented on _posts/2013-12-12-smoke-alert.md
> +Cas sociis natoque penatibus et magnis <a href="#">dis parturient montes</a>, nascetur ridiculus mus. *Aenean eu leo quam.* Pellentesque ornare sem lacinia quam venenatis vestibulum. Sed posuere cons
Não, era apenas para não ficar em branco, e poder ver como ficou o layout.
Porém eu removi.

2020-07-03 06:26 UTC, mastercoks commented on _layouts/404.html
> +  <p>{{ site.translations.error_404.message | default: "Eu sinto muito. Não foi possível encontrar a página que você estava procurando.." }}</p>
Ajustei.

2020-07-03 12:37 UTC, pabrrs requested changes
Excelente trabalho @mastercoks, parabéns :heart_eyes: :clap: :tada: 

Os problemas que notei no mobile foram:

- O celular no topo do site fica em cima do texto

![image](https://user-images.githubusercontent.com/20517508/86469807-8ebb7e00-bd10-11ea-8479-68a3e4052146.png)

- A arte que fica em cima dos botões "quero financiar o projeto" e "quero botar a mão na massa" não se ajustou ao dispositivo

![image](https://user-images.githubusercontent.com/20517508/86469917-c1657680-bd10-11ea-8b8f-9e15f11527c7.png)

2020-07-03 12:37 UTC, pabrrs commented on src/yml/social.yml
> +twitter_username: idvogados
Atualmente, nosso user do twitter é o @idvogados_ofc
```suggestion
twitter_username: idvogados_ofc
```

2020-07-03 12:37 UTC, pabrrs commented on src/yml/social.yml
> +instagram_username: idvogados
Nosso user do instagram é @idvogados.ofc

2020-07-03 12:37 UTC, pabrrs commented on src/yml/social.yml
> +linkedin_username: idvogados
Não tenho certeza se já temos uma página ativa no linkedin, mas existe um `idvogados` lá porém como empresa.

O link normal do Jekyll leva para `/in/idvogados` mas a page no linkedin é `/company/idvogados`.
Existe alguma forma de setar esse path manualmente ?

https://www.linkedin.com/company/idvogados

2020-07-03 21:18 UTC, rodrigondec commented on _config.yml
> +google_analytics: "" #"G-DTG3FDMY4V"
Gostei mt dessa chave aparecendo não. É uma fake? :worried:

2020-07-03 21:18 UTC, rodrigondec commented on src/yml/advanced.yml
> +google_analytics: "" #"G-DTG3FDMY4V"
:worried:

2020-07-04 01:12 UTC, pabrrs commented
Outra coisa que notei, no meta do site vamos setar um favicon e uma descrição no título ? 

![image](https://user-images.githubusercontent.com/20517508/86502496-2dc89000-bd7a-11ea-9997-3f69459df8bd.png)

Acho que é importante

2020-07-05 01:34 UTC, pabrrs commented on _config.yml
> +google_analytics: "" #"G-DTG3FDMY4V"
Acho que temos como fugir de expor essa informação, pois memo usando alguma envvar no código, esse valor fica exposto no html do site quando ele é buildado.

Mas acho válido setarmos uma envvar (talvez usando o secrets do github) para facilitar a manutenção, caso precise mudar.

2020-07-05 03:42 UTC, mastercoks commented on _config.yml
> +google_analytics: "" #"G-DTG3FDMY4V"
Eu ainda irei verificar a opção de configurar como .env, porém n tem muito como esconder essa informação n, uma vez que a solicitação vai ser feita de qq forma.

2020-07-05 03:45 UTC, mastercoks commented
> @mastercoks algumas considerações:
> 
> * No meta do site vamos setar um favicon e uma descrição no título ?
> 
> ![image](https://user-images.githubusercontent.com/20517508/86502496-2dc89000-bd7a-11ea-9997-3f69459df8bd.png)
> 
> * A páginas de **termo de uso** e **privacidade** no footer do site estão levando para páginas que não existem. Pelo menos a página **termos de uso** já temos uma versão no ar http://idvogados.org/termos-de-uso. Acha válido já deixar pronta no site ?

Eu vou configurar o favicon, só tava gerando a imagem, para gerar o manifesto e todo o resto.

quanto a pagina privacidade, ainda não foi me passado o texto da mesma, mas tinha ficado de criar um novo repositório igual o termo de uso, e o link do termo de uso não está funcionando pq o DNS ainda não está configurado, porém quando estiver, ele vai redirecionar para o http://idvogados.org/termos-de-uso

2020-07-30 19:48 UTC, merged